# Generated by Django 2.2.3 on 2019-07-15 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190715_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 15, 26, 59, 2544), verbose_name='Date published'),
        ),
    ]
